<?php

namespace ContainerMVCWRDI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HL0I6eVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HL0I6eV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HL0I6eV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'rdv' => ['privates', '.errored..service_locator.HL0I6eV.App\\Entity\\RDV', NULL, 'Cannot autowire service ".service_locator.HL0I6eV": it needs an instance of "App\\Entity\\RDV" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'rdv' => 'App\\Entity\\RDV',
        ]);
    }
}
