<?php

namespace ContainerMVCWRDI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4C88Vr9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4C88Vr9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4C88Vr9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'consultationRepository' => ['privates', 'App\\Repository\\ConsultationRepository', 'getConsultationRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'consultationRepository' => 'App\\Repository\\ConsultationRepository',
            'entityManager' => '?',
        ]);
    }
}
