<?php

namespace ContainerMVCWRDI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WGNERUiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wGNERUi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wGNERUi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'traitement' => ['privates', '.errored..service_locator.wGNERUi.App\\Entity\\Traitement', NULL, 'Cannot autowire service ".service_locator.wGNERUi": it needs an instance of "App\\Entity\\Traitement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'traitement' => 'App\\Entity\\Traitement',
        ]);
    }
}
