<?php

namespace ContainerMVCWRDI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jvbgp4KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jvbgp4K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jvbgp4K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rdv' => ['privates', '.errored..service_locator.Jvbgp4K.App\\Entity\\RDV', NULL, 'Cannot autowire service ".service_locator.Jvbgp4K": it needs an instance of "App\\Entity\\RDV" but this type has been excluded in "config/services.yaml".'],
        ], [
            'rdv' => 'App\\Entity\\RDV',
        ]);
    }
}
