<?php

namespace ContainerMVCWRDI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EO0FbVW.App\Entity\ProduitCategories' shared service.
     *
     * @return \App\Entity\ProduitCategories
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EO0FbVW": it needs an instance of "App\\Entity\\ProduitCategories" but this type has been excluded in "config/services.yaml".');
    }
}
