<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxE4sdM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxE4sdM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxE4sdM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxE4sdM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGxE4sdM\App_KernelDevDebugContainer([
    'container.build_hash' => 'GxE4sdM',
    'container.build_id' => '85332ff8',
    'container.build_time' => 1741202332,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxE4sdM');
