<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQO7gUtw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQO7gUtw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQO7gUtw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQO7gUtw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQO7gUtw\App_KernelDevDebugContainer([
    'container.build_hash' => 'QO7gUtw',
    'container.build_id' => '63587212',
    'container.build_time' => 1741036830,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQO7gUtw');
