<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQiofIjc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQiofIjc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQiofIjc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQiofIjc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQiofIjc\App_KernelDevDebugContainer([
    'container.build_hash' => 'QiofIjc',
    'container.build_id' => '42ba2cb4',
    'container.build_time' => 1740517874,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQiofIjc');
