<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBTPxbYj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBTPxbYj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBTPxbYj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBTPxbYj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBTPxbYj\App_KernelDevDebugContainer([
    'container.build_hash' => 'BTPxbYj',
    'container.build_id' => '0294af4f',
    'container.build_time' => 1739708260,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBTPxbYj');
