<?php

namespace ContainerSVx8CtB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLigneCommandeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.acTpigy.App\Entity\LigneCommande' shared service.
     *
     * @return \App\Entity\LigneCommande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.acTpigy": it needs an instance of "App\\Entity\\LigneCommande" but this type has been excluded in "config/services.yaml".');
    }
}
