<?php

namespace ContainerVmbzqka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Udb_VtVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Udb.vtV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Udb.vtV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rdvRepository' => ['privates', 'App\\Repository\\RDVRepository', 'getRDVRepositoryService', true],
        ], [
            'rdvRepository' => 'App\\Repository\\RDVRepository',
        ]);
    }
}
