<?php

namespace ContainerVmbzqka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_VOJFHnpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.VOJFHnp' shared service.
     *
     * @return \App\Repository\FournisseurRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AdminController::listFournisseur()": the $fournisseurRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\FournisseurRepository".');
    }
}
