<?php

namespace ContainerVmbzqka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LT33_HtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lT33.ht' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lT33.ht'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ligneCommande' => ['privates', '.errored..service_locator.lT33.ht.App\\Entity\\LigneCommande', NULL, 'Cannot autowire service ".service_locator.lT33.ht": it needs an instance of "App\\Entity\\LigneCommande" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ligneCommande' => 'App\\Entity\\LigneCommande',
        ]);
    }
}
