<?php

namespace ContainerVmbzqka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EO0FbVWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EO0FbVW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EO0FbVW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produitCategorie' => ['privates', '.errored..service_locator.EO0FbVW.App\\Entity\\ProduitCategories', NULL, 'Cannot autowire service ".service_locator.EO0FbVW": it needs an instance of "App\\Entity\\ProduitCategories" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'produitCategorie' => 'App\\Entity\\ProduitCategories',
        ]);
    }
}
