<?php

namespace ContainerVmbzqka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDropForeignKeyCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DropForeignKeyCommand' shared autowired service.
     *
     * @return \App\Command\DropForeignKeyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DropForeignKeyCommand.php';

        $container->privates['App\\Command\\DropForeignKeyCommand'] = $instance = new \App\Command\DropForeignKeyCommand(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));

        $instance->setName('app:drop-fk');

        return $instance;
    }
}
