controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#app_error:
    #path: /error
    #controller: App\Controller\ErrorController::show
    # config/routes.yaml
motivation:
    path: /motivation
    controller: App\Controller\MotivationController::showMotivationalMessage
