parameters:
    dossier_medical_directory: '%kernel.project_dir%/public/uploads/dossier_medical'
    uploads_directory: '%kernel.project_dir%/public/uploads'
    app.issuer: HopeNest

services:
    App\Enum\ExerciceStatus: ~
    # Configuration par défaut pour les services définis dans ce fichier
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    #App\Controller\ErrorController:
      #  tags: ['controller.service_arguments']
    App\Twig\AppExtension:
        arguments:
            $authenticatorService: '@App\Service\AuthenticatorService'
            $security: '@security.helper'
            $logger: '@logger'
        tags: ['twig.extension']    
    # Rend les classes du dossier src/ disponibles en tant que services
    # Cela crée un service par classe avec son nom de classe complet comme identifiant
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Enum/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\PasswordGenerator:
        autowire: true
        # config/services.yaml
    #App\Service\DeepSeekMotivationalMessageService:
        #arguments:
            #$deepSeekApiKey: '%env(DEEPSEEK_API_KEY)%'
#twig:
    #globals:
        #motivational_message: '@App\Service\DeepSeekMotivationalMessageService'
