# Ce fichier est le point d'entrée pour configurer vos services.
# Les fichiers dans le sous-dossier packages/ configurent vos dépendances.

# Ajoutez ici les paramètres qui ne changent pas d'une machine à l'autre
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    # Configuration par défaut pour les services définis dans ce fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, abonnés aux événements, etc.

    # Rend les classes du dossier src/ disponibles en tant que services
    # Cela crée un service par classe avec son nom de classe complet comme identifiant
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Vous pouvez ajouter ici des définitions explicites de services si nécessaire.
    # Les dernières définitions remplacent toujours les précédentes.
