controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#app_error:
    #path: /error
    #controller: App\Controller\ErrorController::show
app_reponse_new:
    path: /response/exercise/{id}/new
    controller: App\Controller\ReponseController::new
    methods: POST

aapp_activite_update_status:
    path: /activite/update-status/{id}
    controller: App\Controller\YourController::updateStatus
    methods: POST

app_patient_show:
    path: /patient/{id}
    controller: App\Controller\PatientController::show
    defaults:
        _format: html
    requirements:
        id: \d+
app_ajouter_panier:
    path: /ajouter-panier/{id}
    controller: App\Controller\ProduitController::ajouterPanier
