<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV0lw05a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV0lw05a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV0lw05a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV0lw05a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV0lw05a\App_KernelDevDebugContainer([
    'container.build_hash' => 'V0lw05a',
    'container.build_id' => 'ef8c3b72',
    'container.build_time' => 1741245085,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV0lw05a');
