<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxGyxWK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxGyxWK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYxGyxWK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYxGyxWK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYxGyxWK\App_KernelDevDebugContainer([
    'container.build_hash' => 'YxGyxWK',
    'container.build_id' => '1d8b1653',
    'container.build_time' => 1739991484,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxGyxWK');
